"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { Archive, ArrowUpRight, AudioLines, Camera, Check, ChevronRight, Compass, ImagePlus, KeyRound, LockKeyhole, MapPin, MessageCircle, MoreHorizontal, Moon, Orbit, Palette, Plus, Radio, Send, Settings2, ShieldCheck, Sparkles, Sun, Video } from "lucide-react";
import { getSupabaseBrowserClient } from "@/lib/supabase/client";
import styles from "@/app/us/universe.module.css";

export type UniverseView = "home" | "chat" | "memories" | "play" | "vault" | "call" | "map" | "settings";
type Member = { space_id: string; user_id: string; role: "owner" | "partner"; shell: "romantic" | "console"; display_name: string; theme: "light" | "dark" | "system" };
type Message = { id: string; sender_id: string; body: string; kind: string; attachment_path: string | null; created_at: string; deleted_at: string | null };
type Memory = { id: string; title: string; note: string; happened_on: string | null; cover_path: string | null; created_at: string };

const nav = [
  ["home", "Home", Compass], ["chat", "Chat", MessageCircle], ["memories", "Memories", Archive], ["play", "Play", Sparkles], ["vault", "Studio", Palette], ["call", "Call", Video], ["map", "Map", MapPin], ["settings", "Settings", Settings2],
] as const;
const quotes = ["A quiet moment can still become a whole story.", "You make the ordinary feel considered.", "A good day gets better when it has somewhere to land.", "Keep the tiny details. They are usually the ones that stay."];

function routeFor(view: UniverseView) { return view === "home" ? "/us" : `/us/${view}`; }
function dayLabel(date: string) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(date)); }

export default function UniverseApp({ view, portal }: { view: UniverseView; portal?: "mine" | "hers" }) {
  const router = useRouter(); const pathname = usePathname();
  const [member, setMember] = useState<Member | null>(null); const [userId, setUserId] = useState("");
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [setup, setSetup] = useState(false);
  const [spaceTitle, setSpaceTitle] = useState("Our Little Universe"); const [displayName, setDisplayName] = useState(""); const [shell, setShell] = useState<"romantic" | "console">("console");
  const [config, setConfig] = useState<Record<string, unknown>>({});
  useEffect(() => { const supabase = getSupabaseBrowserClient(); if (!supabase) { setError("Private access has not been configured."); setLoading(false); return; }
    let active = true;
    void (async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) { router.replace("/hidden-entry"); return; } setUserId(user.id);
      const { data, error: memberError } = await supabase.from("universe_members").select("space_id,user_id,role,shell,display_name,theme").eq("user_id", user.id).maybeSingle();
      if (!active) return; if (memberError) { setError(memberError.message); setLoading(false); return; } if (!data) { setSetup(true); setLoading(false); return; }
      const current = data as Member; setMember(current); const { data: settings } = await supabase.from("universe_settings").select("config").eq("space_id", current.space_id).maybeSingle(); if (active) { setConfig((settings?.config as Record<string, unknown>) ?? {}); setLoading(false); }
    })(); return () => { active = false; };
  }, [router]);
  async function createSpace(event: FormEvent) { event.preventDefault(); const supabase = getSupabaseBrowserClient(); if (!supabase) return; setLoading(true); const { error: rpcError } = await supabase.rpc("bootstrap_universe", { space_title: spaceTitle, member_name: displayName || "Stargazer", member_shell: shell }); if (rpcError) { setError(rpcError.message); setLoading(false); return; } window.location.reload(); }
  if (loading) return <LoadingScreen />;
  if (setup) return <SetupScreen error={error} spaceTitle={spaceTitle} setSpaceTitle={setSpaceTitle} displayName={displayName} setDisplayName={setDisplayName} shell={shell} setShell={setShell} createSpace={createSpace} />;
  if (!member) return <main className={`${styles.universe} ${styles.entry}`}><section className={styles.entryCard}><h1>Access needs attention.</h1><p>{error || "Your private membership could not be loaded."}</p><Link href="/hidden-entry" className={styles.primaryButton}>Return to entry</Link></section></main>;
  const effectiveTheme = member.theme === "system" ? "light" : member.theme;
  const portalDenied = (portal === "mine" && member.role !== "owner") || (portal === "hers" && member.role !== "partner");
  if (portalDenied) return <main className={`${styles.universe} ${styles.entry}`}><section className={styles.entryCard}><div className={styles.eyebrow}><LockKeyhole size={16} /> Private route</div><h1>This side is reserved for its member.</h1><p>Use your own private landing page or return to the shared space.</p><Link href="/us" className={styles.primaryButton}>Open shared space <ArrowUpRight size={16} /></Link></section></main>;
  return <main className={`${styles.universe} ${styles[member.shell]} ${styles[effectiveTheme]}`}>
    <aside className={styles.sidebar}><Link href="/us" className={styles.brand}><span className={styles.brandMark}>U</span><span><b>{member.shell === "romantic" ? "Our little" : "OUR"}</b><small>{member.shell === "romantic" ? "universe" : "LITTLE UNIVERSE"}</small></span></Link>
      <nav aria-label="Private navigation"><Link href={member.role === "owner" ? "/us/mine" : "/us/hers"} className={portal ? styles.navActive : styles.navItem}><Sparkles size={18} /><span>{member.role === "owner" ? "My page" : "My page"}</span></Link>{nav.map(([key, label, Icon]) => <Link key={key} href={routeFor(key)} className={view === key && !portal ? styles.navActive : styles.navItem}><Icon size={18} /><span>{label}</span>{key === "chat" && <i />}</Link>)}</nav>
      <div className={styles.memberCard}><span className={styles.avatar}>{member.display_name.slice(0, 1).toUpperCase()}</span><div><b>{member.display_name}</b><small>{member.role === "owner" ? "Space keeper" : "Connected"}</small></div><button aria-label="Settings" onClick={() => router.push("/us/settings")}><MoreHorizontal size={18} /></button></div>
    </aside>
    <section className={styles.workspace}><header className={styles.topbar}><div><span className={styles.path}>Private space / {view}</span><h1>{titleFor(view)}</h1></div><div className={styles.topActions}><span className={styles.presence}><i /> Together</span><button aria-label="Toggle theme" onClick={async () => { const next = effectiveTheme === "light" ? "dark" : "light"; const supabase = getSupabaseBrowserClient(); await supabase?.from("universe_members").update({ theme: next }).eq("space_id", member.space_id).eq("user_id", member.user_id); setMember({ ...member, theme: next }); }}>{effectiveTheme === "light" ? <Moon size={18} /> : <Sun size={18} />}</button></div></header>
      {view === "home" && <HomeView member={member} config={config} portal={portal ?? (member.role === "owner" ? "mine" : "hers")} />}
      {view === "chat" && <ChatView member={member} userId={userId} />}
      {view === "memories" && <MemoriesView member={member} userId={userId} />}
      {view === "play" && <PlayView member={member} />}
      {view === "vault" && <VaultView member={member} config={config} setConfig={setConfig} />}
      {view === "call" && <CallView />}{view === "map" && <MapView config={config} />}{view === "settings" && <SettingsView member={member} onMember={setMember} />}
    </section>
  </main>;
}

function LoadingScreen() { return <main className={`${styles.universe} ${styles.entry}`}><div className={styles.loading}><Orbit size={30} /><span>Preparing your private space</span></div></main>; }
function SetupScreen(props: { error: string; spaceTitle: string; setSpaceTitle: (v:string)=>void; displayName:string; setDisplayName:(v:string)=>void; shell:"romantic"|"console"; setShell:(v:"romantic"|"console")=>void; createSpace:(e:FormEvent)=>void }) { return <main className={`${styles.universe} ${styles.entry}`}><section className={styles.entryCard}><div className={styles.eyebrow}><Sparkles size={16} /> First setup</div><h1>Create the space<br />you will share.</h1><p>Only use this once, after you have signed in with your own account.</p><form className={styles.entryForm} onSubmit={props.createSpace}><label><span>Space name</span><input value={props.spaceTitle} onChange={e=>props.setSpaceTitle(e.target.value)} required /></label><label><span>Your name here</span><input value={props.displayName} onChange={e=>props.setDisplayName(e.target.value)} placeholder="How should it greet you?" required /></label><fieldset className={styles.shellPicker}><legend>Your interface</legend><button type="button" onClick={()=>props.setShell("romantic")} className={props.shell === "romantic" ? styles.selected : ""}>Soft editorial</button><button type="button" onClick={()=>props.setShell("console")} className={props.shell === "console" ? styles.selected : ""}>Signal console</button></fieldset>{props.error && <p className={styles.formMessage}>{props.error}</p>}<button className={styles.primaryButton}>Create private space <ArrowUpRight size={16} /></button></form></section></main>; }
function titleFor(view: UniverseView) { return ({ home:"A small place for both of you.", chat:"Conversation", memories:"Memory lane", play:"Little rituals", vault:"Experience studio", call:"Call room", map:"Shared location", settings:"Space settings" })[view]; }
function HomeView({ member, config, portal }: { member: Member; config: Record<string, unknown>; portal: "mine" | "hers" }) { return portal === "hers" ? <HerDashboard member={member} quote={String(config.quote ?? quotes[0])} /> : <MyDashboard member={member} quote={String(config.quote ?? quotes[0])} />; }
function HerDashboard({ member, quote }: { member: Member; quote: string }) { return <div className={styles.romanticBoard}><header className={styles.romanticTitle}><span>Our Little Universe</span><small>Just us. Always.</small></header><section className={styles.livingMemories}><div className={styles.boardLabel}>✧ Living memories</div><div className={styles.memoryRibbon}>{["First message","Stargazing night","Beach walk","Our song","Rainy Sunday"].map((item,index)=><article key={item} className={styles.ribbonCard}><div className={`${styles.ribbonArt} ${styles[`art${index}`]}`} /><b>{item}</b><small>{["May 12","Jun 7","Jul 18","Aug 3","Aug 17"][index]}</small></article>)}</div></section><section className={styles.romanticChat}><header><span>✧ Our chat</span><Link href="/us/chat">Video call <Video size={14}/></Link></header><div className={styles.bubbleRow}><span className={styles.miniAvatar}>{member.display_name.slice(0,1)}</span><p>Thinking of you <span>♥</span><small>9:41 AM</small></p></div><div className={`${styles.bubbleRow} ${styles.bubbleRight}`}><p className={styles.voiceBubble}>◉ 〰〰〰〰〰 0:18<small>9:42 AM ✓✓</small></p><span className={styles.miniAvatar}>U</span></div><Link href="/us/chat" className={styles.romanticComposer}>＋ <span>Message my love...</span><span>☺ ♡</span></Link></section><aside className={styles.romanticRail}><div className={styles.profileStack}><span className={styles.largeAvatar}>{member.display_name.slice(0,1)}</span><b>My Love ♥</b><small><i /> Online</small><p>Always here for you ♥</p></div><div className={styles.songCard}><span>♫ Our song</span><div className={styles.songArt}/><b>Sunset Dreams</b><small>by Kina</small><div className={styles.progress}><i /></div><div className={styles.songButtons}>‹ <b>Ⅱ</b> ›</div></div><div className={styles.dateCard}><span>▣ Next special date</span><div><b>AUG<br/><strong>25</strong></b><p>Beach Picnic ☀<br/><small>Saturday, 5:00 PM</small></p></div><small>2 days to go ♡</small></div></aside><footer className={styles.locationBar}>⌾ Sharing location <small>With consent</small><span>On ●</span></footer><p className={styles.dashboardQuote}>“{quote}”</p></div>; }
function MyDashboard({ member, quote }: { member: Member; quote: string }) { return <div className={styles.consoleBoard}><header className={styles.consoleTop}><span><i/> <i/> <i/> PRIVATE CHANNEL // US</span><b>SESSION ACTIVE <small>Supabase Authenticated</small></b></header><aside className={styles.consoleNav}><p>&gt; connection_status: <em>secure</em><br/>&gt; channel: <em>private</em><br/>&gt; participants:<br/><strong>you + her</strong></p>{["Dashboard","Chat","Memory vault","Games","Location"].map((item,index)=><Link href={index===1?"/us/chat":index===2?"/us/memories":index===3?"/us/play":index===4?"/us/map":"/us/mine"} className={index===0?styles.consoleActive:""} key={item}>{["▦","◌","◇","⌘","⌾"][index]} {item}</Link>)}<small>Our constellation.<br/>No one else sees<br/>what we see.</small></aside><section className={styles.consoleMain}><div className={styles.consoleLabel}>▧ MEMORY LOOP <small>enclosed by us</small></div><div className={styles.consoleCarousel}>{["First coffee","Rainy day","Late night talks","Sunset drive","Hand in hand"].map((item,index)=><article className={index===2?styles.consoleSelected:""} key={item}><div className={styles.consoleThumb}>✦</div><b>{item}</b><small>May {12+index}, 2024</small></article>)}</div><div className={styles.consoleLabel}>◌ RECENT CHAT <Link href="/us/chat">View full chat →</Link></div><div className={styles.consoleMessages}><p className={styles.consoleMine}>You<br/><b>Hey beautiful, thinking about you</b><small>11:31 PM ✓✓</small></p><p>Her<br/><b>I was just thinking about you too...</b><small>11:32 PM ♥</small></p><div className={styles.consoleVoice}>◉ &nbsp; 0:07 &nbsp; 〰〰〰〰〰〰〰〰〰 &nbsp; ◼</div><Link href="/us/chat" className={styles.consoleComposer}>Message her... <span>☺ ♡ ➤</span></Link></div></section><aside className={styles.consoleRail}><section><span>♧ PRESENCE</span><b><i/> Online together</b><small>Connected 00:48:21</small></section><section><span>▣ PERMISSIONS</span><b>Control what she sees</b>{["Memories","Location","Surprises","Games"].map(item=><p key={item}>{item}<i/></p>)}</section><section><span>✦ SCHEDULED SURPRISE</span><b>Digital Rose</b><small>Aug 11, 2024 · 09:00 AM</small><Link href="/us/vault">Edit</Link></section><section><span>⇧ UPLOAD TO VAULT</span><p className={styles.uploadWell}>Upload photos, videos, or notes<br/><button>Choose files</button></p></section><section className={styles.callControls}><Link href="/us/call">⌁ Voice call</Link><Link href="/us/call">▣ Video call</Link></section></aside><footer className={styles.consoleFooter}>&gt; channel_encryption: end_to_end &nbsp; &gt; data_residency: private &nbsp; &gt; access: you &amp; her <span>time together: 47d 13h 26m ♡</span></footer><p className={styles.consoleQuote}>// {quote}</p></div>; }
function ChatView({ member, userId }: { member: Member; userId:string }) { const [messages,setMessages]=useState<Message[]>([]); const [text,setText]=useState(""); const [typing,setTyping]=useState(false); const [remoteTyping,setRemoteTyping]=useState(false); const [sending,setSending]=useState(false); const fileRef=useRef<HTMLInputElement>(null); const channelRef=useRef<any>(null);
  useEffect(()=>{ const supabase=getSupabaseBrowserClient(); if(!supabase)return; let channel:any; void supabase.from("universe_messages").select("id,sender_id,body,kind,attachment_path,created_at,deleted_at").eq("space_id",member.space_id).is("deleted_at",null).order("created_at",{ascending:true}).then(({data})=>setMessages((data??[]) as Message[])); channel=supabase.channel(`universe:${member.space_id}:chat`,{config:{private:true}}).on("broadcast",{event:"typing"},({payload}:{payload:{userId:string; active:boolean}})=>{if(payload.userId!==userId)setRemoteTyping(payload.active)}).on("postgres_changes",{event:"INSERT",schema:"public",table:"universe_messages",filter:`space_id=eq.${member.space_id}`},({new:row})=>setMessages(old=>old.some(x=>x.id===row.id)?old:[...old,row as Message])).subscribe(); channelRef.current=channel; return()=>{channelRef.current=null;if(channel)supabase.removeChannel(channel);};},[member.space_id,userId]);
  async function submit(event:FormEvent){event.preventDefault();if(!text.trim())return;const supabase=getSupabaseBrowserClient();if(!supabase)return;setSending(true);const body=text.trim();setText("");await supabase.from("universe_messages").insert({space_id:member.space_id,sender_id:userId,client_id:crypto.randomUUID(),body,kind:"text"});setSending(false);}
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];const supabase=getSupabaseBrowserClient();if(!file||!supabase)return;setSending(true);const path=`${member.space_id}/${userId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const {error}=await supabase.storage.from("universe-media").upload(path,file,{upsert:false});if(!error)await supabase.from("universe_messages").insert({space_id:member.space_id,sender_id:userId,client_id:crypto.randomUUID(),body:file.name,kind:file.type.startsWith("image/")?"image":"video",attachment_path:path});setSending(false); event.target.value="";}
  function signalTyping(active:boolean){setTyping(active);void channelRef.current?.send({type:"broadcast",event:"typing",payload:{userId,active}});}
  return <div className={styles.chatLayout}><section className={styles.chatPanel}><header><div><span className={styles.kicker}>Private conversation</span><h2>Just the two of you</h2></div><span className={styles.presence}><i /> Connected</span></header><div className={styles.messages}>{messages.length===0?<div className={styles.emptyState}><MessageCircle size={28}/><b>Nothing here yet.</b><p>The first note can be small.</p></div>:messages.map(message=><article key={message.id} className={message.sender_id===userId?styles.mine:styles.theirs}><span>{message.body}</span><small>{dayLabel(message.created_at)}</small></article>)}{remoteTyping&&<p className={styles.typing}>Someone is typing<span>.</span><span>.</span><span>.</span></p>}</div><form className={styles.composer} onSubmit={submit}><input ref={fileRef} type="file" accept="image/*,video/mp4,audio/*" onChange={upload} hidden/><button type="button" onClick={()=>fileRef.current?.click()} aria-label="Attach media"><ImagePlus size={20}/></button><button type="button" aria-label="Voice notes coming soon" disabled><AudioLines size={20}/></button><textarea value={text} onChange={e=>{setText(e.target.value);signalTyping(Boolean(e.target.value));}} onBlur={()=>signalTyping(false)} placeholder="Write a message..." rows={1}/><button disabled={sending||!text.trim()} aria-label="Send message"><Send size={19}/></button></form></section><aside className={styles.chatAside}><span className={styles.kicker}>Private channel</span><h3>Messages are stored in your shared space.</h3><p>Attachments live in a private bucket and are only accessible to space members.</p><div className={styles.securityNote}><ShieldCheck size={19}/>Authenticated membership controls access.</div></aside></div>; }
function MemoriesView({member,userId}:{member:Member;userId:string}) { const [memories,setMemories]=useState<Memory[]>([]);const [open,setOpen]=useState(false);const [title,setTitle]=useState("");const [note,setNote]=useState("");useEffect(()=>{const s=getSupabaseBrowserClient();void s?.from("universe_memories").select("id,title,note,happened_on,cover_path,created_at").eq("space_id",member.space_id).order("created_at",{ascending:false}).then(({data})=>setMemories((data??[])as Memory[]));},[member.space_id]);async function add(e:FormEvent){e.preventDefault();const s=getSupabaseBrowserClient();const {data}=await s!.from("universe_memories").insert({space_id:member.space_id,title,note,created_by:userId,happened_on:new Date().toISOString().slice(0,10)}).select("id,title,note,happened_on,cover_path,created_at").single();if(data)setMemories([data as Memory,...memories]);setOpen(false);setTitle("");setNote("");}return <div><div className={styles.sectionHead}><p>A shared archive for the things worth keeping.</p><button className={styles.primaryButton} onClick={()=>setOpen(true)}><Plus size={17}/> Add a memory</button></div>{open&&<form className={styles.inlineForm} onSubmit={add}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="A title for this moment" required/><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="What do you want to remember?"/><button className={styles.primaryButton}>Save it</button><button type="button" className={styles.textButton} onClick={()=>setOpen(false)}>Cancel</button></form>}<div className={styles.memoryGrid}>{memories.length?memories.map((memory,index)=><article className={styles.memoryCard} key={memory.id}><div className={styles.memoryNumber}>0{index+1}</div><span>{memory.happened_on||"A day worth keeping"}</span><h2>{memory.title}</h2><p>{memory.note}</p><button className={styles.textButton} onClick={()=>navigator.clipboard?.writeText(`${memory.title}\n${memory.note}`)}>Copy memory <ArrowUpRight size={15}/></button></article>):<div className={styles.emptyState}><Archive size={30}/><b>No memories yet.</b><p>Add your first shared moment.</p></div>}</div></div>; }
function PlayView({member}:{member:Member}){const [mood,setMood]=useState("");const [accepted,setAccepted]=useState(false);const [noCount,setNoCount]=useState(0);return <div className={styles.playGrid}><section className={styles.feelingCard}><span className={styles.kicker}>A small check-in</span><h2>How are you, really?</h2><p>Pick the feeling that is closest to today. The other person will see it here.</p><div className={styles.moodGrid}>{["Light","Thoughtful","Need a hug","Quiet day"].map(item=><button className={mood===item?styles.moodSelected:""} key={item} onClick={()=>setMood(item)}>{item}</button>)}</div>{mood&&<p className={styles.formMessage}><Check size={15}/> Shared: {mood}</p>}</section><section className={styles.questionCard}><span className={styles.kicker}>One playful question</span><h2>{accepted?"Yay. When do we make it happen?":"Would a hug make today better?"}</h2><p>{accepted?"Put it in the chat and turn the answer into a plan.":noCount?"Wacha kukimbilia no. Jaribu tena pole pole.":"There is no pressure, just a little room for a smile."}</p>{!accepted&&<div className={styles.questionActions}><button className={styles.primaryButton} onClick={()=>setAccepted(true)}>Yes, please</button><button className={styles.outlineButton} style={{transform:noCount?`translate(${Math.min(noCount*22,90)}px,${noCount%2?12:-8}px)`:undefined}} onClick={()=>setNoCount(v=>v+1)}>Not today</button></div>}</section></div>;}
function VaultView({member,config,setConfig}:{member:Member;config:Record<string,unknown>;setConfig:(v:Record<string,unknown>)=>void}){const [quote,setQuote]=useState(String(config.quote??""));const [status,setStatus]=useState("");async function save(e:FormEvent){e.preventDefault();const s=getSupabaseBrowserClient();const next={...config,quote};const {error}=await s!.from("universe_settings").update({config:next,version:Number(config.version??1)+1}).eq("space_id",member.space_id);if(error){setStatus(error.message);return;}setConfig(next);setStatus("Saved as a new private revision.");}if(member.role!=="owner")return <div className={styles.emptyState}><LockKeyhole size={30}/><b>The studio belongs to the space keeper.</b><p>Shared views stay available to both people.</p></div>;return <div className={styles.studioLayout}><section><span className={styles.kicker}>Experience studio</span><h2>Shape the atmosphere, not the access controls.</h2><p>The interface is revisioned here. Membership and permissions stay protected.</p></section><form className={styles.studioForm} onSubmit={save}><label>Rotating welcome quote<textarea value={quote} onChange={e=>setQuote(e.target.value)} rows={4}/></label><label>Current interface<div className={styles.readOnly}>{member.shell === "romantic" ? "Soft editorial" : "Signal console"}</div></label>{status&&<p className={styles.formMessage}>{status}</p>}<button className={styles.primaryButton}>Save private revision <ArrowUpRight size={16}/></button></form></div>;}
function CallView(){return <section className={styles.callPanel}><div><span className={styles.kicker}>Call room</span><h2>Start only when both people are ready.</h2><p>Video calls need a configured LiveKit provider to issue short-lived server tokens. This page does not pretend a browser camera is a secure call.</p><button className={styles.primaryButton} disabled><Video size={18}/> Live calling is not configured</button></div><div className={styles.callPreview}><Camera size={38}/><span>Camera preview stays off until a call is joined.</span></div></section>}
function MapView({config}:{config:Record<string,unknown>}){const enabled=config.allow_location===true;return <section className={styles.mapPanel}><div><span className={styles.kicker}>Location consent</span><h2>Location is off by default.</h2><p>When location sharing is enabled, each person chooses the precision and expiry before anything is sent.</p><button className={styles.outlineButton} disabled={!enabled}>{enabled?"Request live location":"Location sharing is disabled"}</button></div><div className={styles.mapCanvas}><MapPin size={38}/><span>No live coordinates</span></div></section>}
function SettingsView({member,onMember}:{member:Member;onMember:(m:Member)=>void}){const [name,setName]=useState(member.display_name);async function save(e:FormEvent){e.preventDefault();const s=getSupabaseBrowserClient();await s?.from("universe_members").update({display_name:name}).eq("space_id",member.space_id).eq("user_id",member.user_id);onMember({...member,display_name:name});}return <div className={styles.settingsForm}><form onSubmit={save}><span className={styles.kicker}>Your identity in this space</span><label>Display name<input value={name} onChange={e=>setName(e.target.value)} /></label><button className={styles.primaryButton}>Save profile</button></form><section><span className={styles.kicker}>Privacy status</span><div className={styles.securityNote}><ShieldCheck size={20}/><p><b>Membership secured</b><br/>Only authenticated space members can access shared records.</p></div><div className={styles.securityNote}><Radio size={20}/><p><b>Realtime restricted</b><br/>Private channels are reserved for the shared space.</p></div></section>{member.role === "owner" && <InvitePartner member={member} />}</div>}
function InvitePartner({member}:{member:Member}){const [email,setEmail]=useState("");const [name,setName]=useState("");const [message,setMessage]=useState("");async function invite(e:FormEvent){e.preventDefault();const s=getSupabaseBrowserClient();if(!s)return;const {data:{session}}=await s.auth.getSession();const response=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/functions/v1/universe-invite`,{method:"POST",headers:{Authorization:`Bearer ${session?.access_token??""}`,"Content-Type":"application/json"},body:JSON.stringify({email,displayName:name,spaceId:member.space_id})});const body=await response.json().catch(()=>({}));setMessage(body.error??"Invitation sent. They can create a password from the secure email.");}return <form className={styles.inviteForm} onSubmit={invite}><span className={styles.kicker}>Invite your person</span><p>They receive their own authenticated entry. No shared password is needed.</p><input type="email" placeholder="Their email address" value={email} onChange={e=>setEmail(e.target.value)} required/><input placeholder="Their display name" value={name} onChange={e=>setName(e.target.value)} required/><button className={styles.primaryButton}>Send private invitation</button>{message&&<p className={styles.formMessage}>{message}</p>}</form>}
