insert into public.cms_documents (workspace_id, kind, slug, title, status, draft_body, published_body, published_at)
values
  ('7ec3d48f-4435-4fd8-9651-2e0739c8cdd3', 'project', 'business-pack-catalogue-flow', 'Business Pack Catalogue Flow', 'published', '{"eyebrow":"Business Pack","summary":"A product discovery flow included as part of a broader business website pack.","body":"Products, filters and enquiry flow."}'::jsonb, '{"eyebrow":"Business Pack","summary":"A product discovery flow included as part of a broader business website pack.","body":"Products, filters and enquiry flow."}'::jsonb, now()),
  ('7ec3d48f-4435-4fd8-9651-2e0739c8cdd3', 'project', 'ack-st-pauls-karen-west', 'ACK St. Pauls Karen West Concept', 'published', '{"eyebrow":"Church Site","summary":"A structured church concept for ministries, services, media and clear contact interactions.","body":"Services, ministries and events."}'::jsonb, '{"eyebrow":"Church Site","summary":"A structured church concept for ministries, services, media and clear contact interactions.","body":"Services, ministries and events."}'::jsonb, now()),
  ('7ec3d48f-4435-4fd8-9651-2e0739c8cdd3', 'project', 'portfolio-generator', 'Portfolio Generator', 'published', '{"eyebrow":"Reusable System","summary":"Reusable portfolio sections and deployment patterns for job seekers and freelancers.","body":"Themes, profiles and GitHub Pages."}'::jsonb, '{"eyebrow":"Reusable System","summary":"Reusable portfolio sections and deployment patterns for job seekers and freelancers.","body":"Themes, profiles and GitHub Pages."}'::jsonb, now()),
  ('7ec3d48f-4435-4fd8-9651-2e0739c8cdd3', 'project', 'ai-document-studio', 'AI Document Studio', 'published', '{"eyebrow":"Documents","summary":"Branded letters, forms, certificates and PDF-generation workflows for organisations.","body":"PDF, forms and branding."}'::jsonb, '{"eyebrow":"Documents","summary":"Branded letters, forms, certificates and PDF-generation workflows for organisations.","body":"PDF, forms and branding."}'::jsonb, now()),
  ('7ec3d48f-4435-4fd8-9651-2e0739c8cdd3', 'project', 'cybersecurity-learning-lab', 'Cybersecurity Learning Lab', 'published', '{"eyebrow":"Learning","summary":"A safe public learning record for cybersecurity progress, notes and lab modules.","body":"Notes, labs and network basics."}'::jsonb, '{"eyebrow":"Learning","summary":"A safe public learning record for cybersecurity progress, notes and lab modules."}'::jsonb, now()),
  ('7ec3d48f-4435-4fd8-9651-2e0739c8cdd3', 'project', '3d-farm-marketplace', '3D Farm Marketplace', 'published', '{"eyebrow":"3D Commerce","summary":"Lightweight 3D product views paired with a cleaner store direction and scalable payment paths.","body":"Three.js, products and checkout."}'::jsonb, '{"eyebrow":"3D Commerce","summary":"Lightweight 3D product views paired with a cleaner store direction and scalable payment paths."}'::jsonb, now()),
  ('7ec3d48f-4435-4fd8-9651-2e0739c8cdd3', 'project', 'audio-technical-services', 'Audio and Technical Services Concept', 'published', '{"eyebrow":"Booking Site","summary":"Service packages, booking prompts and technical support information in one place.","body":"Packages, booking and support."}'::jsonb, '{"eyebrow":"Booking Site","summary":"Service packages, booking prompts and technical support information in one place."}'::jsonb, now())
on conflict (workspace_id, kind, slug) do nothing;
